//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWebsite.Shared.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Days_Friday {
            get {
                return ResourceManager.GetString("Days_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Days_Monday {
            get {
                return ResourceManager.GetString("Days_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Days_Saturday {
            get {
                return ResourceManager.GetString("Days_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Days_Sunday {
            get {
                return ResourceManager.GetString("Days_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Days_Thursday {
            get {
                return ResourceManager.GetString("Days_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Days_Tuesday {
            get {
                return ResourceManager.GetString("Days_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Days_Wednesday {
            get {
                return ResourceManager.GetString("Days_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aban.
        /// </summary>
        public static string Months_Aban {
            get {
                return ResourceManager.GetString("Months_Aban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azar.
        /// </summary>
        public static string Months_Azar {
            get {
                return ResourceManager.GetString("Months_Azar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahman.
        /// </summary>
        public static string Months_Bahman {
            get {
                return ResourceManager.GetString("Months_Bahman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dey.
        /// </summary>
        public static string Months_Dey {
            get {
                return ResourceManager.GetString("Months_Dey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfand.
        /// </summary>
        public static string Months_Esfand {
            get {
                return ResourceManager.GetString("Months_Esfand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farvardin.
        /// </summary>
        public static string Months_Farvardin {
            get {
                return ResourceManager.GetString("Months_Farvardin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khordad.
        /// </summary>
        public static string Months_Khordad {
            get {
                return ResourceManager.GetString("Months_Khordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr.
        /// </summary>
        public static string Months_Mehr {
            get {
                return ResourceManager.GetString("Months_Mehr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mordad.
        /// </summary>
        public static string Months_Mordad {
            get {
                return ResourceManager.GetString("Months_Mordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordibehesht.
        /// </summary>
        public static string Months_Ordibehesht {
            get {
                return ResourceManager.GetString("Months_Ordibehesht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shahrivar.
        /// </summary>
        public static string Months_Shahrivar {
            get {
                return ResourceManager.GetString("Months_Shahrivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tir.
        /// </summary>
        public static string Months_Tir {
            get {
                return ResourceManager.GetString("Months_Tir", resourceCulture);
            }
        }
    }
}
