# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

        # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mssql:
        # Docker Hub image
        image: mcr.microsoft.com/mssql/server:2019-latest
        # Provide the password for postgres
        env:
          ACCEPT_EULA: Y 
          MSSQL_SA_PASSWORD: Abcd1234@
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
         node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c TEST --no-restore
    - name: Test
      run: dotnet test -c TEST --environment "ASPNETCORE_ENVIRONMENT=Test" --no-build --verbosity normal
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
